name: Build and Test
# 1. Build and test WecOptTool
#   - check that WecOptTool builds on a matrix of OS + Python versions
#   - check that all tests pass on the same matrix
#   - report the test code coverage
# 2. Check that the documentation builds correctly

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  wecopttool_test:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.11", "3.12"]  # CHANGE: Python version

    steps:
    # Checkout the WecOptTool repo
    - uses: actions/checkout@v3

    # Caching of environment has been removed for simplicity
    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: test-env

    # install libglu on ubuntu.
    - name: Install libglu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libglu1

    # install WecOptTool, pytest/coveralls, and gmsh/pygmsh
    - name: Install WecOptTool
      shell: bash -l {0}
      run: |
        conda activate test-env
        python3 -m pip install --upgrade pip
        pip3 install gmsh pygmsh coveralls pytest
        pip3 install -e .

    # run all tests & coverage
    - name: Run Test
      shell: bash -l {0}
      run: coverage run -m pytest

    # upload coverage data
    - name: Upload coverage data to coveralls.io
      shell: bash -l {0}
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.os }}-${{ matrix.python-version }}
        COVERALLS_PARALLEL: true


  coveralls:
    name: Indicate completion to coveralls.io
    needs: wecopttool_test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  documentation_test:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # CHANGE: Python version

    - name: Install dependencies
      run: sudo apt-get install libglu1 pandoc gifsicle
      
    - name: Install WecOptTool for documentation
      shell: bash -l {0}
      run: |
        python3 -m pip install --upgrade pip
        pip3 install wheel coveralls
        pip3 install -e .[dev,geometry]

    - name: Build documentation
      shell: bash -l {0}
      run: |
        git fetch --tags
        python3 docs/build_docs.py --build production
